Assignment 1 - Scenario - I should be able to fetch all posts, and all comments for user with id '1'
znsio/getting-started-with-karate pull request #4
Opened 2022-12-14 12:36 UTC by AmanDaharwal

2022-12-14 18:05 UTC, MSR-K requested changes
Please incorporate review comments!

2022-12-14 18:05 UTC, mshahrukh2 commented on src/test/java/com/znsio/api/posts.feature
> +
Feature name doesn't match what tests are inside it. It has comment Api tests also.

2022-12-14 18:05 UTC, mshahrukh2 commented on src/test/java/com/znsio/api/posts.feature
> +  Feature: Api tests for https://jsonplaceholder.typicode.com/
Prefer not to mention URL in  here. Please use appropriate feature description.

2022-12-14 18:05 UTC, mshahrukh2 commented on src/test/java/com/znsio/templates/postsTemplates.feature
> +      Given path "/posts/"+ postId +"/comments"
Why we are fetching comments based on postId? Assignment is to fetch comments for user 1. Let's discuss if you have any doubts .

2022-12-14 18:05 UTC, mshahrukh2 commented on src/test/java/com/znsio/templates/postsTemplates.feature
> +      And print "Response for get comments for user " + response
Use karate.log() in place of print statement.

2022-12-14 18:05 UTC, mshahrukh2 commented on src/test/java/com/znsio/api/posts.feature
> +    Scenario: User should be able to fetch all the comments for user 1
Please check templates comment for this scenario

2022-12-14 18:05 UTC, MSR-K commented on src/test/java/com/znsio/templates/createPostPayload.json
> +{
How will you manage multiple data json here?

2022-12-14 18:05 UTC, MSR-K commented on src/test/java/com/znsio/templates/updatePostPayload.json
> +{
Can be defined in single JSONs file where all template data is available.

2022-12-14 18:05 UTC, MSR-K commented on src/test/java/com/znsio/templates/updatePostPayload.json
> +  "title": "djhakds",
Use randomiser feature to generate random string! would be more efficient.

2022-12-14 18:05 UTC, MSR-K commented on src/test/java/test_data.json
> +      "postsUrl": "https://jsonplaceholder.typicode.com"
Wrong url naming convention.

2022-12-14 18:05 UTC, MSR-K commented on src/test/java/com/znsio/api/posts.feature
> +      * def postId = 8
Please go through scenario again.

2022-12-15 06:48 UTC, AmanDaharwal commented on src/test/java/test_data.json
> +      "postsUrl": "https://jsonplaceholder.typicode.com"
Done, updated

2022-12-15 06:53 UTC, AmanDaharwal commented on src/test/java/com/znsio/api/posts.feature
> +
updated name

2022-12-15 06:56 UTC, AmanDaharwal commented on src/test/java/com/znsio/api/posts.feature
> +  Feature: Api tests for https://jsonplaceholder.typicode.com/
removed url

2022-12-15 07:00 UTC, AmanDaharwal commented on src/test/java/com/znsio/templates/postsTemplates.feature
> +      And print "Response for get comments for user " + response
Done

2022-12-19 04:56 UTC, MSR-K commented on src/test/java/com/znsio/api/jsonPlaceHolderSchema.json
> +{
This File is located in wrong directory.

2022-12-19 04:56 UTC, MSR-K commented on src/test/java/com/znsio/api/jsonPlaceHolder.feature
> +      * def id = 10
* def id = 10 -Is this required?

2022-12-19 04:56 UTC, MSR-K commented on src/test/java/com/znsio/templates/jsonPlaceHolderTemplate.feature
> +    And print "Post Url : "+env.jsonPlaceHolderUrl
Why do we need to print URL?

2022-12-19 04:56 UTC, MSR-K commented on src/test/java/com/znsio/workflow/jsonPlaceHolderTemplate.feature
> +      Given def postedUserResponse = karate.call('classpath:com/znsio/templates/postsTemplates.feature@t_postPostsForUser', {'jsonPayload' : jsonPayload , 'expectedStatus': 201}).postForUser
This is wrong !. First verify the Response of fist API call then if its working ok then call another API.

2022-12-19 04:56 UTC, MSR-K commented on src/test/java/com/znsio/workflow/jsonPlaceHolderTemplate.feature
> +      And def postedUserResponse2 = karate.call('classpath:com/znsio/templates/postsTemplates.feature@t_postPostsForUser', 'expectedStatus' : 200 ).postForUser
Same as above

2024-02-12 05:52 UTC, closed without merging